Question 1

In [1]:
import numpy as np

Question 2

In [3]:
x = np.empty((3,3))
x

array([[4.88507891e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

question 3

In [4]:
x = np.ones((6,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Question 4

In [5]:
x=np.full((4,3),3)

question 5

In [6]:
p=np.arange(6).reshape(2,3)
a=np.zeros_like(p)
a

array([[0, 0, 0],
       [0, 0, 0]])

question 6

In [7]:
p=np.arange(8).reshape(2,4)
x=np.ones_like(p)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

question 7

In [8]:
new_list=[1,2,3,4]
K=np.array(new_list)
K

array([1, 2, 3, 4])

question 8

In [9]:
b=np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

question 9

In [10]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

question 10

In [11]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

question 11

In [12]:
x = np.random.random(30)
mean = x.mean()

print("array given: ", x)
print("Mean  : ", mean)

array given:  [0.17130095 0.93065661 0.21659829 0.56637729 0.34228874 0.42976771
 0.72830568 0.49572542 0.11460324 0.93139361 0.02639317 0.53779488
 0.99485655 0.18002691 0.55842981 0.34269108 0.82565526 0.13080594
 0.3471098  0.4745845  0.65109492 0.302003   0.50279783 0.84160181
 0.4971625  0.72956168 0.58231018 0.15060928 0.23349841 0.45782434]
Mean  :  0.476460979582878


question 12

In [13]:
b=np.random.random((10,10))
min=b.min()
max=b.max()
print("Array: ", b)
print("Min:", min)
print("Max:", max)

Array:  [[0.11911559 0.19700056 0.53129437 0.26729404 0.00464911 0.29720388
  0.44936034 0.44434852 0.87890439 0.55800982]
 [0.29962567 0.17931397 0.79837488 0.12605809 0.89849301 0.02353333
  0.32817334 0.08496365 0.71349557 0.17097847]
 [0.56315304 0.09073405 0.56112492 0.62067496 0.15079669 0.8124329
  0.86483438 0.71794721 0.78483929 0.92310387]
 [0.52684448 0.51730475 0.08495593 0.77441465 0.75274687 0.10894526
  0.67620327 0.53232759 0.93838972 0.8949346 ]
 [0.62068261 0.58550638 0.13574149 0.79486576 0.83343209 0.10632381
  0.73320791 0.69303652 0.85376528 0.45163144]
 [0.98721083 0.54906885 0.26591489 0.81733055 0.32053316 0.97957826
  0.99672944 0.01224867 0.37384985 0.10854604]
 [0.17656257 0.47358305 0.06589738 0.48864305 0.07690714 0.65161321
  0.46206449 0.05736146 0.26426862 0.95912151]
 [0.05594762 0.36456464 0.4464307  0.36456605 0.24499659 0.25451102
  0.95091069 0.17270373 0.24372367 0.2349072 ]
 [0.90735483 0.28899021 0.64437112 0.97602115 0.12652407 0.6023855
  0.50

question 13

In [14]:
b=np.zeros(10)
b[4]=1
print("Updated :", b)

Updated : [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


question 14

In [15]:
b=np.array([1,2,0,0,4,0])
rev=b[::-1]
print("Original: ", b)
print("reversed: ", rev)

Original:  [1 2 0 0 4 0]
reversed:  [0 4 0 0 2 1]


question 15

In [16]:
b=np.zeros((5,5),dtype=int)
b[0,:]=1 #top
b[-1,:]=1 #bottom
b[:,0]=1 #left
b[:,-1]=1 #right
print("1 on border and 0 inside : ",b)


1 on border and 0 inside :  [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


question 16

In [17]:
b=np.zeros((8,8))
b[1::2,::2]=1
b[::2,1::2]=1
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

question 17

In [18]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
x3 = np.array([9,10])
y3 = np.array([11,12])
print("x: \n",x)
print("y: \n",y)
add=x+y
add3=x3+y3
print("Adding x+y: \n",add)
print("x3: \n",x3)
print("y3: \n",y3)
print("adding x3+y3: ",add3)

x: 
 [[1 2]
 [3 5]]
y: 
 [[5 6]
 [7 8]]
Adding x+y: 
 [[ 6  8]
 [10 13]]
x3: 
 [ 9 10]
y3: 
 [11 12]
adding x3+y3:  [20 22]


question 18

In [19]:
sub=x-y
sub3=x3-y3
print("subtracting y from x: ",sub)
print("subtracting y3 from x3: ",sub3)

subtracting y from x:  [[-4 -4]
 [-4 -3]]
subtracting y3 from x3:  [-2 -2]


question 19

In [20]:
mul_x=x*2
mul_x
mul_y=y*2
mul_y
mul_x3=x3*2
mul_x3
mul_y3=y3*2
mul_y3

array([22, 24])

question 20

In [21]:
sq_x=np.square(x)
print("squaring x: \n",sq_x )
sq_y=np.square(y)
print("squaring y: \n",sq_y )
sq_x3=np.square(x3)
print("squaring x3: \n",sq_x3 )
sq_y3=np.square(y3)
print("squaring y3: \n",sq_y3 )

squaring x: 
 [[ 1  4]
 [ 9 25]]
squaring y: 
 [[25 36]
 [49 64]]
squaring x3: 
 [ 81 100]
squaring y3: 
 [121 144]


question 21

In [22]:
result = np.dot(x3, y3)
result
result_1 = np.dot(x, x3)
result_1
result_2 = np.dot(x, y)
result_2

array([[19, 22],
       [50, 58]])

question 22

In [23]:
a=np.concatenate((x,y),axis=1)
print(a)
a=np.vstack((x3,y3))
print(a)

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 10]
 [11 12]]


question 23

In [25]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x3 = np.array([[7, 8, 9]])


result = np.concatenate((x, x3), axis=0)
print("Concatenation result:\n", result)

Concatenation result:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


question 24

In [26]:

A1=np.array([[3,4],[7,8]])
B1=np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A1)
result=np.dot(A1,A_inverse)
identity_matrix=np.eye(2)
print("Matrix A1:\n", A1)
print("Inverse of A1 (A^-1):\n", A_inverse)
print("Product of A1 and A^-1 (A.A^-1):\n", result)
print("Identity Matrix:\n", identity_matrix)
y=np.allclose(result,identity_matrix)
print("Is A.A^-1 equal to identity matrix?->",y)

Matrix A1:
 [[3 4]
 [7 8]]
Inverse of A1 (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product of A1 and A^-1 (A.A^-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Is A.A^-1 equal to identity matrix?-> True


question 25

In [27]:
A1B1 = np.dot(A1, B1)
B1A1 = np.dot(B1, A1)
print("A1B1 (A1 * B1):\n", A1B1)
print("B1A1 (B1 * A1):\n", B1A1)
are_equal=np.array_equal(A1B1,B1A1)
print(" Is A1B1 = B1A1? ",are_equal)

A1B1 (A1 * B1):
 [[23 13]
 [51 29]]
B1A1 (B1 * A1):
 [[36 44]
 [13 16]]
 Is A1B1 = B1A1?  False


question 26

In [28]:
A1 = np.array([[1, 2], [3, 4]])
B1 = np.array([[5, 6], [7, 8]])
AB=np.dot(A1,B1)
AB_T=AB.T
B_T=B1.T
A_T=A1.T
BT_AT=np.dot(B_T,A_T)
print("AB:\n", AB)
print("(AB)^T:\n", AB_T)
print("B^T:\n", B_T)
print("A^T:\n", A_T)
print("B^T * A^T:\n", BT_AT)
is_equal=np.array_equal(AB_T,BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", is_equal)

AB:
 [[19 22]
 [43 50]]
(AB)^T:
 [[19 43]
 [22 50]]
B^T:
 [[5 7]
 [6 8]]
A^T:
 [[1 3]
 [2 4]]
B^T * A^T:
 [[19 43]
 [22 50]]
Is (AB)^T equal to B^T * A^T?  True


question 27

In [29]:
A1=np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B1=np.array([-1,-3,9])
A_inverse=np.linalg.inv(A1)
x=np.dot(A_inverse,B1)
print( A1)
print( B1)
print( A_inverse)
print( x)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
[-1 -3  9]
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
[ 2.  1. -2.]


question 28

In [30]:

import time
l3=list(range(1,1000001))
l4=list(range(1,1000001))
start_time= time.time()
result_list=[a+b for a, b in zip(l3,l4)]
python_time=time.time()-start_time
print(" Python lists time:", python_time, "seconds")
#numpy arrays:
a3=np.arange(1,1000001)
a4=np.arange(1,1000001)

start_time=time.time()
result_array=a3+a4
numpy_time=time.time()-start_time
print(" NumPy arrays time:", numpy_time, "seconds")


 Python lists time: 0.10822582244873047 seconds
 NumPy arrays time: 0.003948688507080078 seconds


question 29

In [31]:

start_time=time.time()
result_list=[a*b for a,b in zip(l3,l4)]
python_time=time.time()-start_time
print("multiplication using Python lists time:", python_time, "seconds")

start_time = time.time()
result_array = a3 * a4
numpy_time = time.time() - start_time
print(" multiplication using NumPy arrays:", numpy_time, "seconds")

multiplication using Python lists time: 0.10672330856323242 seconds
 multiplication using NumPy arrays: 0.005113363265991211 seconds


question 30

In [32]:



start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(l3, l4))
python_time = time.time() - start_time
print( python_time, "seconds")



start_time = time.time()
dot_product_numpy = np.dot(a3, a4)
numpy_time = time.time() - start_time
print( numpy_time, "seconds")

0.12412071228027344 seconds
0.0023441314697265625 seconds


question 31

In [33]:
import time
import numpy as np

# Python lists
m3 = [[i for i in range(100)] for j in range(100)]
m4 = [[i for i in range(100)] for j in range(100)]

start_time = time.time()
result_matrix = [[sum(m3[i][k] * m4[k][j] for k in range(100)) for j in range(100)] for i in range(100)]
python_time = time.time() - start_time
print(" Python lists time:", python_time, "seconds")

# Matrix multiplication using NumPy
m3_np = np.random.rand(100, 100)
m4_np = np.random.rand(100, 100)

start_time = time.time()
result_matrix_np = np.dot(m3_np, m4_np)
numpy_time = time.time() - start_time
print("MNumPy arrays time:", numpy_time, "seconds")

 Python lists time: 0.17827916145324707 seconds
MNumPy arrays time: 0.0005166530609130859 seconds
